import datetime
from ai.insight_engine import generate_marketing_insights

def build_comprehensive_report(metrics: dict, aud_metrics: list, forecast_metrics: list) -> str:
    """Assembles data components into a full markdown report wrapping AI analysis."""
    
    core_insights = generate_marketing_insights(metrics, aud_metrics, forecast_metrics)
    
    if "Error:" in core_insights:
        return f"Report generation failed due to AI Service error: {core_insights}"
        
    report_md = f"""# AdPulse AI Comprehensive Marketing Report
*Generated on: {datetime.date.today().strftime('%B %d, %Y')}*

{core_insights}

---
*Report auto-generated by AdPulse AI Analytics Engine*
"""
    return report_md
